<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Docker.DotNet" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CodeLab.Domain\CodeLab.Domain.csproj" />
  </ItemGroup>
</Project>
