<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog"/>
    <PackageReference Include="Serilog.AspNetCore"/>
    <PackageReference Include="Serilog.Enrichers.Environment"/>
    <PackageReference Include="Serilog.Enrichers.Thread"/>
    <PackageReference Include="Serilog.Exceptions"/>
    <PackageReference Include="Serilog.Exceptions.EntityFrameworkCore"/>
    <PackageReference Include="Serilog.Extensions.Hosting"/>
    <PackageReference Include="Serilog.Extensions.Logging"/>
    <PackageReference Include="Serilog.Settings.Configuration"/>
    <PackageReference Include="Serilog.Sinks.Async"/>
    <PackageReference Include="Serilog.Sinks.Console"/>
    <PackageReference Include="Serilog.Sinks.Debug"/>
    <PackageReference Include="Serilog.Sinks.Seq"/>
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger"/>
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen"/>
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CodeLab.CodeRunner\CodeLab.CodeRunner.csproj" />
    <ProjectReference Include="..\CodeLab.Core\CodeLab.Core.csproj"/>
    <ProjectReference Include="..\CodeLab.Domain\CodeLab.Domain.csproj"/>
    <ProjectReference Include="..\CodeLab.Infrastructure.Postgres\CodeLab.Infrastructure.Postgres.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
  </ItemGroup>
</Project>
