// <auto-generated />
using System;
using CodeLab.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeLab.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228153043_Add_TestItem")]
    partial class Add_TestItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeLab.Domain.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_exercises");

                    b.ToTable("exercises", (string)null);
                });

            modelBuilder.Entity("CodeLab.Domain.Submissions.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id")
                        .HasName("pk_submissions");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("ix_submissions_exercise_id");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("CodeLab.Domain.Submissions.Submission", b =>
                {
                    b.HasOne("CodeLab.Domain.Exercises.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_exercises_exercise_id");

                    b.OwnsMany("CodeLab.Domain.Submissions.TestItem", "TestResults", b1 =>
                        {
                            b1.Property<Guid>("SubmissionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Message")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Status")
                                .HasColumnType("integer");

                            b1.HasKey("SubmissionId", "__synthesizedOrdinal")
                                .HasName("pk_submissions");

                            b1.ToTable("submissions");

                            b1.ToJson("test_results");

                            b1.WithOwner()
                                .HasForeignKey("SubmissionId")
                                .HasConstraintName("fk_submissions_submissions_submission_id");
                        });

                    b.Navigation("TestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
