// <auto-generated />
using System;
using CodeLab.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeLab.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeLab.Domain.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AssignedDate")
                        .HasColumnType("date")
                        .HasColumnName("assigned_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MarkdownContent")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("markdown_content");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_exercises");

                    b.HasIndex("AssignedDate")
                        .IsUnique()
                        .HasDatabaseName("ix_exercises_assigned_date");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_exercises_slug");

                    b.ToTable("exercises", (string)null);
                });

            modelBuilder.Entity("CodeLab.Domain.Submissions.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("source_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id")
                        .HasName("pk_submissions");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("ix_submissions_exercise_id");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("CodeLab.Domain.Submissions.Submission", b =>
                {
                    b.HasOne("CodeLab.Domain.Exercises.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_exercises_exercise_id");

                    b.OwnsOne("CodeLab.Domain.Submissions.TestResult", "TestResult", b1 =>
                        {
                            b1.Property<Guid>("SubmissionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Message")
                                .HasColumnType("text");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SubmissionId");

                            b1.ToTable("submissions");

                            b1.ToJson("test_result");

                            b1.WithOwner()
                                .HasForeignKey("SubmissionId")
                                .HasConstraintName("fk_submissions_submissions_id");

                            b1.OwnsMany("CodeLab.Domain.Submissions.TestItem", "TestItems", b2 =>
                                {
                                    b2.Property<Guid>("TestResultSubmissionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Output")
                                        .HasColumnType("text");

                                    b2.Property<string>("Status")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("TestResultSubmissionId", "__synthesizedOrdinal");

                                    b2.ToTable("submissions");

                                    b2.ToJson("test_result");

                                    b2.WithOwner()
                                        .HasForeignKey("TestResultSubmissionId")
                                        .HasConstraintName("fk_submissions_submissions_test_result_submission_id");
                                });

                            b1.Navigation("TestItems");
                        });

                    b.Navigation("TestResult");
                });
#pragma warning restore 612, 618
        }
    }
}
